```{r} 
#Instalamos librerias 

library(dplyr) 

library(readxl) 

library(openxlsx) 

library(ggplot2) 

library(gridExtra)

library(tidyverse)

library(gridExtra)
```


````{r} 
rm(list=ls())
```


 
```{r} 
#Load data 
datap <- read_excel("C:/Users/marce/Downloads/SurveyReport-11068686-05-09-2023-T184330.161.xlsx", sheet = "Datos sin procesar") 

#Modfy the first rows
datap <- datap %>% slice(3:n()) 

#Create a segment by age
datap <- datap %>% mutate(segmento = if_else(`¿Cuál es tu edad?` >= 27, 'Adultos', 'Joven')) 
datap
```

```{r} 
#Saco los valores unicos y sus relaciones, y evaluo. 
## Valores categoria funcional 
data_funcional <- as.data.frame(c('Me disguta que sea así', 'Puedo aceptar que sea de esa manera ', 'Soy neutral', 'Esperaría que sea así', 'Me gustaría')) ### Rename columnas 
colnames(data_funcional)<-'funcional' 
### Etiqueto y ordeno valores 
data_funcional$funcional <- factor(data_funcional$funcional, levels = c('Me disguta que sea así', 'Puedo aceptar que sea de esa manera ', 'Soy neutral', 'Esperaría que sea así', 'Me gustaría')) 



## Valores categoria disfuncional 
data_disfuncional <- as.data.frame(c('Me disguta que sea así', 'Puedo aceptar que sea de esa manera ', 'Soy neutral', 'Esperaría que sea así', 'Me gustaría')) 
### Rename columnas 
colnames(data_disfuncional)<-'disfuncional' 

### Etiqueto y ordeno valores 
data_disfuncional$disfuncional <- factor(data_disfuncional$disfuncional, levels = c('Me disguta que sea así', 'Puedo aceptar que sea de esa manera ', 'Soy neutral', 'Esperaría que sea así', 'Me gustaría')) 


# Hago un crossjoin para tener todas las posibles combinaciones 
## Creo una varaible constante 
data_disfuncional$const <- 1 
data_funcional$const <- 1 
#Ejecuto crossjoin 

data_matriz <- inner_join(data_funcional,data_disfuncional, by='const')
data_matriz <- data_matriz %>% select(funcional,disfuncional) 


#etiqueto cada uno de los cruces con los valores constantes 
data_matriz$valoracion <- c(  'Q', 'R', 'R', 'R', 'R', 'M', 'Q', 'I', 'I', 'R', 'M', 'I', 'I', 'I', 'R','O', 'I', 'I', 'Q', 'R', 'O', 'O', 'A', 'A', 'Q')


#agrego una descripcion a las etiquetas 

desvaloracion <- as.data.frame(unique(data_matriz$valoracion)) %>% arrange() 
colnames(desvaloracion) <- c('valoracion') 
desvaloracion$des_valoracion <-c('Questionable','Inversa','Obligatoria','Indiferente','De desempeño','Atractiva') 
data_matriz <- inner_join(data_matriz,desvaloracion) %>%select(funcional,disfuncional,des_valoracion) 
colnames(data_matriz) <- c('funcional','disfuncional','valoracion') 

#Convierto a tipo data string 
data_matriz$funcional <- as.character(data_matriz$funcional) 
data_matriz$disfuncional<-as.character(data_matriz$disfuncional) 


#Eliminamos objetos que no vamos a utilziar 

rm(list=c('data_disfuncional','data_funcional','desvaloracion'))

data_matriz

```




```{r} 
#Creo etiquetas de colores para el análisis, que siempre tenga los mismos colores cada etiqueta 

m_valoracion <- as.data.frame(unique(data_matriz$valoracion)) %>% arrange() 
m_valoracion$color <- c('purple','black','#ffcd16','#999999','#4aaf47','#1a78be') 
colnames(m_valoracion) <- c('valoracion','color') 
m_valoracion <-setNames(as.character(m_valoracion$color), m_valoracion$valoracion) 

m_valoracion


## Creo data de calificaciones por cada una de las caracteristicas 

valor_funcional <- as.data.frame(unique(data_matriz$funcional)) 
valor_funcional$valor <- c(-2,-1,0.5,2,4) 
colnames(valor_funcional) <- c('funcional','valor funcional') 
valor_funcional

## Creo data de calificaciones por cada una de las caracteristicas 
valor_disfuncional <- as.data.frame(unique(data_matriz$disfuncional)) 
valor_disfuncional$valor <- c(4,2,0.5,-1,-2) 
colnames(valor_disfuncional) <- c('disfuncional','valor disfuncional') 
valor_disfuncional



```



```{r}
#Creo objetos para la interacion de cada una de las funciones

caract_total_segmento <- data.frame(matrix(ncol = 6, nrow = 0)) 
caract_total<- data.frame(matrix(ncol = 5, nrow = 0)) 
caracteristicas_total <-data.frame(matrix(ncol = 3, nrow = 0)) 
caract_semgment_uni_total <-data.frame(matrix(ncol = 6, nrow = 0)) 
caract_uni_total <-data.frame(matrix(ncol = 5, nrow = 0)) 
caract_uni_feat_total <-data.frame(matrix(ncol = 5, nrow = 0))
caract_semgment <-data.frame(matrix(ncol = 6, nrow = 0)) 

#Genero listado para obtener el par de columnas de cada iteracion
numeros <- seq(19, 57, by = 2)
# Configurar los márgenes de la hoja del PDF
pdf("Matriz Kano Informe.pdf", width = 8.27, height = 11.69, onefile = TRUE)

#Creo la iteracion para que por cada funcionalidad genere una analisis de las calificaciones por encuesta.

for (i in numeros) {

  ##Filtro las calificaciones (columnas) de cada funcionalidad
data <- datap[, c(1, i, (i + 1),71)] 
colnames(data) <- c('id', 'funcional','disfuncional','segmento')

##Cruzamos la matriz de valoración para la generación de la matriz de desempeño

data <- inner_join(data,valor_funcional, by = 'funcional') 
data <- inner_join(data,valor_disfuncional, by= 'disfuncional' )
## Agregamos la valoración a la matriz de análisis.

data$funcion <-names(datap)[i] 
data <- inner_join(data, data_matriz, by = c('disfuncional', 'funcional')) %>% as.data.frame()

# Realizamos las agrupaciones para la graficacion

data_analisis <- data %>% 
              group_by(funcion,funcional, disfuncional,segmento) %>%
              summarise(Valor = length(id), 
                        Funcional = sum(`valor funcional`), 
                        Disfuncional = sum(`valor disfuncional`), 
                        .groups = "drop" )
##Agregamos la etiqueta de la clificacion cruzada 

data_analisis <-inner_join(data_analisis, data_matriz, by = c('disfuncional', 'funcional')) %>%
                                                      as.data.frame()

###Creamos el df para la valoracion de caracteristicas x segmento
### Tomando el mayor valor las categorias de calificacion x segmento

caract_semgment_uni <- data %>% group_by(funcion, funcional,disfuncional,segmento, valoracion) %>%
                                            summarise(Valor=length(unique(id)),
                                                      Funcional=sum(`valor funcional`), 
                                                      Disfuncional=sum(`valor disfuncional`),
                                                      .groups = "drop") %>%
                                            group_by(funcion,segmento)%>% 
                                            filter(Valor == max(Valor)) %>%                                            select(funcion,segmento,valoracion,Valor,Funcional,Disfuncional) %>%
                                            as.data.frame() 

####Creamos dataframen donde consolidamos las mejoras calificaciones x segmento

caract_semgment_uni_total <-rbind(caract_semgment_uni_total,caract_semgment_uni)

### Tomando el mayor valor las categorias de calificacion global

caract_uni <- data %>% group_by(funcion, funcional, disfuncional, valoracion) %>%
                      summarise(Valor=length(unique(id)), 
                                Funcional=sum(`valor funcional`),
                                Disfuncional=sum(`valor disfuncional`),
                                .groups = "drop") %>% 
                        group_by(funcion)%>% filter(Valor== max(Valor)) %>%
                        select(funcion,valoracion,Valor,Funcional,Disfuncional) %>%
                        as.data.frame()

####Creamos dataframen donde consolidamos las mejoras calificaciones

caract_uni_total <- rbind(caract_uni_total,caract_uni)

#Consolidamos las valoraciones ganadores de cada etiqueta para graficas (p1)

caract_uni_feat <- data %>% 
  group_by(funcion, funcional, disfuncional,valoracion ) %>%
  summarise(Valor=length(unique(id)), 
            Funcional=sum(`valor funcional`), 
            Disfuncional=sum(`valor disfuncional`),.groups = "drop") %>%
  group_by(funcion,
           valoracion)%>% 
  filter(Valor == max(Valor)) %>%
  select(funcion,
         valoracion,
         Valor,
         Funcional,
         Disfuncional) %>% as.data.frame()


####Creamos dataframen donde consolidamos las valoraciones ganadores de cada etiqueta para graficas (p1)

caract_uni_feat_total <-rbind(caract_uni_feat_total,caract_uni_feat)

##Etiqueto los valores de las columnas para ordenar los ejes en el  gráfico

data_analisis$funcional <- factor(data_analisis$funcional, levels = c('Me disguta que sea así', 
                                                                      'Puedo aceptar que sea de esa manera ', 
                                                                      'Soy neutral',
                                                                      'Esperaría que sea así', 
                                                                      'Me gustaría'))

data_analisis$disfuncional <- factor(data_analisis$disfuncional, levels = c('Me disguta que sea así', 
                                                                            'Puedo aceptar que sea de esa manera ',
                                                                            'Soy neutral',
                                                                            'Esperaría que sea así', 
                                                                            'Me gustaría'))

#Creamos df donde se consolidan el analisis de cada funcion

caracteristicas_total <- rbind(caracteristicas_total, data_analisis)

# Configurar los márgenes del gráfico 

par(mar = c(7, 7, 4, 2))
# Calcular el tamaño de los gráficos 

grafico_width <- 0.4 * (8.27 - 2)  # 40% del ancho de la hoja, restando los márgenes izquierdo y derecho
grafico_height <- (11.69 - 2) / 2  # Mitad del alto de la hoja, restando los márgenes superior e inferior


##Creamos grafico de expresiones cruzadas funcionales y disfuncionales

p <- ggplot(data=data_analisis) + geom_point(aes(y = funcional, 
                                                 x = disfuncional, 
                                                 size = Valor,
                                                 color = valoracion)) +
  labs(title = names(datap)[i],
       y = "Funcional", 
       x = "Disfuncional") + 
  scale_size_continuous(range = c(1, 8)) +
  scale_color_manual(values = m_valoracion)+ 
  theme_minimal() + 
  theme(axis.text.x = element_text(angle = 25, hjust = 1))

data_fun <- caract_uni_feat

p 

# Obtener el punto con el mayor valor #Consolidamos las valoraciones ganadores de cada etiqueta para graficas

punto_max_valor <- data_fun[data_fun$Valor ==max(data_fun$Valor), ]

p1 <-  ggplot(data = data_fun) + 
  geom_point(aes(x = Funcional, 
                 y = Disfuncional,
                 col = valoracion, 
                 size = Valor)) + 
  labs(x = "Funcional", 
       y = "Disfuncional",
       title = names(datap)[i]) + 
  scale_color_manual(values = m_valoracion) +
  theme(axis.text = element_blank()) + 
  theme_minimal() + # Resaltar el punto con el mayor valor 
  geom_point(data = punto_max_valor, aes(x = Funcional, 
                                         y = Disfuncional), 
             col = "red", size = 0.5) + 
  geom_text(data = punto_max_valor,
            aes(x = Funcional, 
                y = Disfuncional, 
                label = valoracion), 
            vjust = -1.5, 
            col ="black", 
            size = 4, 
            show.legend = FALSE)

# Crear una nueva página en el archivo PDF con dos gráficos uno arriba y otro abajo 

grid.arrange(p, p1, nrow = 2, heights = c(grafico_height, grafico_height),widths = c(grafico_width)) 
}

p1

# Cerrar el archivo PDF 

dev.off()

p
p1


```

```{r}
#Muestra del grafico de evaluacion de caraacteristicas library(ggplot2)
p <-  ggplot(data=data_analisis) + 
      geom_point(aes(y = funcional, 
                     x = disfuncional, 
                     size = Valor,
                     color = valoracion)) + 
  labs(title = names(datap)[i],
       y = "Funcional", 
       x = "Disfuncional") + 
  scale_size_continuous(range = c(1, 8)) +
  scale_color_manual(values = m_valoracion)+ 
  theme_minimal() + 
  theme(axis.text.x =element_text(angle = 25, hjust = 1))
print(p)
```



````{r} 
#Desarrollo grafico de performance global. 

##Creo data para el desarrollo del ejercicio 

data_fun <- caract_uni_total%>% as.data.frame() 

# Enumerar las funciones 

data_fun$num_funcion <- seq_along(data_fun$funcion) 

valores_excluidos <- c(13) 

data_fun <- data_fun %>% filter(!(num_funcion %in% valores_excluidos)) 
data_fun$num_funcion <- seq_along(data_fun$funcion) 

# Gráfico con enumeración de funciones y líneas guía 

ggplot(data = data_fun) + 
  geom_point(aes(x = Funcional, 
                 y = Disfuncional, 
                 col = valoracion, 
                 size = Valor)) + 
  geom_label(aes(x = Funcional, 
                 y = Disfuncional, 
                 label = num_funcion), 
             vjust = -1.5, 
             label.padding = unit(0.15, "lines"), 
             label.size = 0.25, 
             fill = "white", 
             color = "black", 
             show.legend = FALSE) + 
  geom_segment(aes(x = Funcional, 
                   y = Disfuncional, 
                   xend = Funcional, 
                   yend = Disfuncional), 
               data = data_fun, 
               color = "black", 
               alpha = 0.4, 
               show.legend = FALSE) + 
  geom_vline(xintercept = mean(data_fun$Funcional), 
             linetype = "solid", 
             color = "red") + 
  geom_hline(yintercept = mean(data_fun$Disfuncional)*1.4, 
             linetype = "solid", color = "red") + 
  labs(x = "Funcional", 
       y = "Disfuncional",
       title = "Valoración Funcionalidades Global") + 
  annotate("text", x = 250, y = 0, label = "Atractivo", hjust = 1, vjust = 1, col = "#145f97") + 
  annotate("text", x = 250, y = 290, label = "Desempeño", hjust = 1, vjust = 1, col = "#4aaf47") + 
  annotate("text", x = 0, y = 0, label = "Indiferente", hjust = 0, vjust = 0, col = "#999999") + 
  annotate("text", x = 0, y = 290, label = "Obligatorio", hjust = 0, vjust = 0, col = "#ffcd16") + 
  scale_color_manual(values = m_valoracion) + 
  theme(axis.text = element_blank()) + 
  theme_minimal() 

````











